using System.Text;
using Motus.Recorder.PageAnalysis;

namespace Motus.Recorder.PomEmit;

/// <summary>
/// Emits a strongly-typed C# partial class (Page Object Model) from discovered page elements.
/// </summary>
public sealed class PomEmitter
{
    /// <summary>
    /// Generates a <c>.g.cs</c> file containing a partial page object class.
    /// </summary>
    public string Emit(IReadOnlyList<DiscoveredElement> elements, PomEmitOptions? options = null)
    {
        options ??= new PomEmitOptions();
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Motus.Abstractions;");
        sb.AppendLine();
        sb.AppendLine($"namespace {options.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {options.ClassName}");
        sb.AppendLine("{");

        // Constructor and navigation
        sb.AppendLine("    private readonly IPage _page;");
        sb.AppendLine();
        sb.AppendLine($"    public {options.ClassName}(IPage page) => _page = page;");
        sb.AppendLine();
        sb.AppendLine($"    public Task NavigateAsync() => _page.GotoAsync(\"{EscapeString(options.PageUrl)}\");");

        // Locators
        if (elements.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    // Locators");
            foreach (var el in elements)
            {
                if (el.Selector is not null)
                {
                    sb.AppendLine($"    public ILocator {el.MemberName} => _page.Locator(\"{EscapeString(el.Selector)}\");");
                }
                else
                {
                    sb.AppendLine($"    // TODO: No unique selector found for {el.MemberName} ({el.Info.Tag}[{el.Info.ElementIndex}])");
                }
            }
        }

        // Form actions
        var formGroups = FormGrouper.GroupByForm(elements);
        if (formGroups.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    // Form actions");
            foreach (var group in formGroups)
            {
                EmitFormAction(sb, group);
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitFormAction(StringBuilder sb, FormGrouper.FormGroup group)
    {
        // Build method name from submit button
        var methodName = $"Submit{group.SubmitButton!.MemberName.Replace("Button", "")}FormAsync";

        // Build parameter list
        var parameters = new List<string>();
        foreach (var input in group.FillableInputs)
        {
            var paramName = ToCamelCase(input.MemberName.Replace("Input", "").Replace("Element", ""));
            if (string.IsNullOrEmpty(paramName))
                paramName = $"field{input.Info.ElementIndex}";
            parameters.Add($"string {paramName}");
        }

        sb.AppendLine($"    public async Task {methodName}({string.Join(", ", parameters)})");
        sb.AppendLine("    {");

        // Fill calls
        var paramIndex = 0;
        foreach (var input in group.FillableInputs)
        {
            var paramName = ToCamelCase(input.MemberName.Replace("Input", "").Replace("Element", ""));
            if (string.IsNullOrEmpty(paramName))
                paramName = $"field{input.Info.ElementIndex}";
            sb.AppendLine($"        await {input.MemberName}.FillAsync({paramName});");
            paramIndex++;
        }

        // Submit click
        sb.AppendLine($"        await {group.SubmitButton.MemberName}.ClickAsync();");
        sb.AppendLine("    }");
    }

    private static string ToCamelCase(string pascalCase)
    {
        if (string.IsNullOrEmpty(pascalCase))
            return pascalCase;
        return char.ToLowerInvariant(pascalCase[0]) + pascalCase[1..];
    }

    private static string EscapeString(string value)
        => value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
}
